apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.xnatWeb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.xnatWeb.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.xnatWeb.name }}
    spec:
      containers:
      - env:
        - name: XNAT_VER
          value: {{ .Values.xnatWeb.env.version }}
        - name: CATALINA_OPTS
          value: {{ .Values.xnatWeb.env.catalinaOpts }}
        - name: XNAT_HOME
          value: {{ .Values.xnatWeb.env.folders.home }}
        - name: XNAT_ROOT
          value: {{ .Values.xnatWeb.env.folders.root }}
        - name: XNAT_DATASOURCE_DRIVER
          value: {{ .Values.xnatWeb.env.dataSource.driver }}
        - name: XNAT_DATASOURCE_URL
          value: {{ .Values.xnatWeb.env.dataSource.url }}
        - name: XNAT_DATASOURCE_USERNAME
          value: {{ .Values.xnatWeb.env.dataSource.username }}
        - name: XNAT_DATASOURCE_PASSWORD
          value: {{ .Values.xnatWeb.env.dataSource.password }}
        - name: XNAT_HIBERNATE_DIALECT
          value: {{ .Values.xnatWeb.env.dataSource.dialect }}
        - name: TOMCAT_XNAT_FOLDER
          value: {{ .Values.xnatWeb.env.folders.tomcat }}
        - name: ACTIVEMQ_BROKER_URL
          value: {{ .Values.xnatWeb.env.mq.brokerUrl }}
        - name: ACTIVEMQ_USER
          value: {{ .Values.xnatWeb.env.mq.username }}
        - name: ACTIVEMQ_PASSWORD
          value: {{ .Values.xnatWeb.env.mq.password }}
        - name: MAX_FILE_SIZE
          value: "{{ .Values.xnatWeb.env.multipart.maxFileSize }}"
        - name: MAX_REQUEST_SIZE
          value: "{{ .Values.xnatWeb.env.multipart.maxRequestSize }}"
        image: {{ .Values.xnatWeb.image }}
        command: ["/bin/bash", "-c"]
        args: [{{ .Values.xnatWeb.args }}]
        imagePullPolicy: Always
        name: {{ .Values.xnatWeb.name }}
        ports:
        - containerPort: {{ .Values.xnatWeb.ports.web8080 }}
          protocol: TCP
        - containerPort: {{ .Values.xnatWeb.ports.web8000 }}
          protocol: TCP
        - containerPort: {{.Values.xnatWeb.ports.ssh22 }}
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: {{ .Values.xnatWeb.plugins.volumes }}
          name: {{ .Values.xnatWeb.name }}-claim0
        - mountPath: {{ .Values.xnatWeb.logs.volumes }}
          name: {{ .Values.xnatWeb.name }}-claim1
        - mountPath: {{ .Values.xnatWeb.archive.volumes }}
          name: {{ .Values.xnatWeb.name }}-claim2
        - mountPath: {{ .Values.xnatWeb.build.volumes }}
          name: {{ .Values.xnatWeb.name }}-claim3
        - mountPath: {{ .Values.xnatWeb.dockerSock.volumes }}
          name: {{ .Values.xnatWeb.name }}-claim4
        - mountPath: {{ .Values.xnatWeb.config.bin }}/{{ .Values.xnatWeb.config.xnat.script }}
          subPath: {{ .Values.xnatWeb.config.xnat.script }}
          name: {{ .Values.xnatWeb.config.xnat.name }}
        - mountPath: {{ .Values.xnatWeb.config.bin }}/{{ .Values.xnatWeb.config.postgres.script }}
          subPath: {{ .Values.xnatWeb.config.postgres.script }}
          name: {{ .Values.xnatWeb.config.postgres.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Values.xnatWeb.config.xnat.name }}
        configMap:
          name: {{ .Values.xnatWeb.config.xnat.name }}
          defaultMode: 0777
      - name: {{ .Values.xnatWeb.config.postgres.name }}
        configMap: 
          name: {{ .Values.xnatWeb.config.postgres.name }}
          defaultMode: 0777
      - name: {{ .Values.xnatWeb.name }}-claim0
        persistentVolumeClaim:
          claimName: {{ .Values.xnatWeb.name }}-claim0
      - name: {{ .Values.xnatWeb.name }}-claim1
        persistentVolumeClaim:
          claimName: {{ .Values.xnatWeb.name }}-claim1
      - name: {{ .Values.xnatWeb.name }}-claim2
        persistentVolumeClaim:
          claimName: {{ .Values.xnatWeb.name }}-claim2
      - name: {{ .Values.xnatWeb.name }}-claim3
        persistentVolumeClaim:
          claimName: {{ .Values.xnatWeb.name }}-claim3
      - name: {{ .Values.xnatWeb.name }}-claim4
        persistentVolumeClaim:
          claimName: {{ .Values.xnatWeb.name }}-claim4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.xnatDb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.xnatDb.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.xnatDb.name }}
    spec:
      containers:
      - env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: {{ .Values.xnatDb.authMethod }}
        image: {{ .Values.xnatDb.image }}
        imagePullPolicy: Always
        name: {{ .Values.xnatDb.name }}
        ports:
        - containerPort: {{ .Values.xnatDb.ports }}
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: {{ .Values.xnatDb.volumes.data }}
          name: {{ .Values.xnatDb.name }}-claim0
        - mountPath: {{ .Values.xnatDb.init.path }}/{{ .Values.xnatDb.init.script }}
          subPath: {{ .Values.xnatDb.init.script }}
          name: {{ .Values.xnatDb.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Values.xnatDb.name }}
        configMap:
          name: {{ .Values.xnatDb.name }}
      - name: {{ .Values.xnatDb.name }}-claim0
        persistentVolumeClaim:
          claimName: {{ .Values.xnatDb.name }}-claim0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.xnatMq.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.xnatMq.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.xnatMq.name }}
    spec:
      containers:
      - env:
        - name: ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT
          value: "{{ .Values.xnatMq.env.config.removeDefaultAccount }}"
        - name: ACTIVEMQ_ENABLED_SCHEDULER
          value: "{{ .Values.xnatMq.env.config.enabledScheduler }}"
        - name: ACTIVEMQ_MIN_MEMORY
          value: "{{ .Values.xnatMq.env.config.minMemory }}"
        - name: ACTIVEMQ_MAX_MEMORY
          value: "{{ .Values.xnatMq.env.config.maxMemory }}"
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: {{ .Values.xnatMq.env.users.admin.login }}
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: {{ .Values.xnatMq.env.users.admin.password }}
        - name: ACTIVEMQ_WRITE_LOGIN
          value: {{ .Values.xnatMq.env.users.write.login }}
        - name: ACTIVEMQ_WRITE_PASSWORD
          value: {{ .Values.xnatMq.env.users.write.password }}
        - name: ACTIVEMQ_READ_LOGIN
          value: {{ .Values.xnatMq.env.users.read.login }}
        - name: ACTIVEMQ_READ_PASSWORD
          value: {{ .Values.xnatMq.env.users.read.password }}
        - name: ACTIVEMQ_JMX_LOGIN
          value: {{ .Values.xnatMq.env.users.jmx.login }}
        - name: ACTIVEMQ_JMX_PASSWORD
          value: {{ .Values.xnatMq.env.users.jmx.password }}
        image: {{ .Values.xnatMq.image }}
        imagePullPolicy: Always
        name: {{ .Values.xnatMq.name }}
        ports:
        - containerPort: {{ .Values.xnatMq.ports.adminUi }}
          protocol: TCP
        - containerPort: {{ .Values.xnatMq.ports.mq }}
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: {{ .Values.xnatMq.volumes.data }}
          name: {{ .Values.xnatMq.name }}-claim0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Values.xnatMq.name }}-claim0
        persistentVolumeClaim:
          claimName: {{ .Values.xnatMq.name }}-claim0
