apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.xnatWeb.name }}-claim0
  name: {{ .Values.xnatWeb.name }}-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.xnatWeb.plugins.request }}
  selector:
    matchLabels:
      name: {{ .Values.xnatWeb.name }}-volume0
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.xnatWeb.name }}-claim1
  name: {{ .Values.xnatWeb.name }}-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.xnatWeb.logs.request }}
  selector:
    matchLabels:
      name: {{ .Values.xnatWeb.name }}-volume1
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.xnatWeb.name }}-claim2
  name: {{ .Values.xnatWeb.name }}-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.xnatWeb.archive.request }}
  selector:
    matchLabels:
      name: {{ .Values.xnatWeb.name }}-volume2
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.xnatWeb.name }}-claim3
  name: {{ .Values.xnatWeb.name }}-claim3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.xnatWeb.build.request }}
  selector:
    matchLabels:
      name: {{ .Values.xnatWeb.name }}-volume3
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.xnatWeb.name }}-claim4
  name: {{ .Values.xnatWeb.name }}-claim4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.xnatWeb.dockerSock.request }}
  selector:
    matchLabels:
      name: {{ .Values.xnatWeb.name }}-volume4
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.xnatDb.name }}-claim0
  name: {{ .Values.xnatDb.name }}-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.xnatDb.request }}
  selector:
    matchLabels:
      name: {{ .Values.xnatDb.name }}-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.xnatMq.name }}-claim0
  name: {{ .Values.xnatMq.name }}-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.xnatMq.request }}
  selector:
    matchLabels:
      name: {{ .Values.xnatMq.name }}-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: xnat-pacs-claim0
  name: xnat-pacs-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: xnat-pacs-volume
